Repository Clinical-Genomics/trailblazer, pull requests merged in 2023-11, with the labels that each got.

#294 feat(end-point): Remove unused query-analyses
  trailblazer/server/api.py
Labels: Project Task

#295 Refactor analyses
  tests/conftest.py
  tests/store/filters/test_analysis_filters.py
  tests/store/test_base.py
  trailblazer/server/api.py
  trailblazer/store/api.py
  trailblazer/store/base.py
  trailblazer/store/crud/read.py
  trailblazer/store/filters/analyses_filters.py
Labels: Project Task

#297 feat(refactor): Basehandle
  tests/mocks/store_mock.py
  tests/store/utils/store_helper.py
  trailblazer/cli/core.py
  trailblazer/server/ext.py
  trailblazer/store/api.py
  trailblazer/store/base.py
  trailblazer/store/core.py
  trailblazer/store/crud/create.py
  trailblazer/store/crud/delete.py
  trailblazer/store/crud/read.py
  trailblazer/store/crud/update.py
Labels: Project Task

#312 Refactor to pep 0585
  tests/apps/slurm/test_api.py
  tests/apps/slurm/test_models.py
  tests/apps/tower/test_tower_api.py
  tests/cli/test_cli_core.py
  tests/conftest.py
  tests/io/test_io_csv.py
  tests/store/crud/test_create.py
  tests/store/crud/test_delete.py
  tests/store/crud/test_read.py
  tests/store/crud/test_update.py
  trailblazer/apps/slurm/api.py
  trailblazer/apps/slurm/models.py
  trailblazer/apps/slurm/utils/formatters.py
  trailblazer/apps/tower/api.py
  trailblazer/apps/tower/models.py
  trailblazer/cli/core.py
  trailblazer/cli/utils/ls_helper.py
  trailblazer/constants.py
  trailblazer/io/controller.py
  trailblazer/io/csv.py
  trailblazer/server/api.py
  trailblazer/store/base.py
  trailblazer/store/crud/read.py
  trailblazer/store/crud/update.py
  trailblazer/store/database.py
  trailblazer/store/filters/analyses_filters.py
  trailblazer/store/filters/job_filters.py
  trailblazer/store/filters/user_filters.py
  trailblazer/utils/datetime.py
Labels: Enhancement

#316 fix check is_analysis_failed
  trailblazer/apps/slurm/api.py
Labels: Bug

#317 feat(refactor): StrEnum
  tests/conftest.py
  tests/store/crud/test_update.py
  trailblazer/apps/slurm/models.py
  trailblazer/apps/tower/api.py
  trailblazer/constants.py
  trailblazer/store/crud/create.py
  trailblazer/store/crud/update.py
  trailblazer/store/models.py
Labels: Enhancement
